#!/usr/bin/env bash

# source this file, then call provision_swtpm_patch_identity <amd|intel>

: "${ROOT_ESC:=sudo}"
_tpmp_info() { if declare -f fmtr::info  >/dev/null 2>&1; then fmtr::info  "$*"; else echo "[i] $*"; fi; }
_tpmp_warn() { if declare -f fmtr::warn  >/dev/null 2>&1; then fmtr::warn  "$*"; else echo "[!] $*" >&2; fi; }
_tpmp_dns_ips() {
    local hostname=$1
    python3 -c '
import sys, xml.etree.ElementTree as ET
hostname = sys.argv[1].lower().rstrip(".")
root = ET.fromstring(sys.stdin.read())
seen = set()
for host in root.findall("./dns/host"):
    names = [(node.text or "").lower().rstrip(".") for node in host.findall("./hostname")]
    address = host.get("ip", "")
    if hostname in names and address not in seen:
        seen.add(address)
        print(address)
' "$hostname"
}

provision_swtpm_patch_identity() {
    local vendor="${1:-amd}"
    local source_dir
    source_dir=$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")
    local patcher="${LIBTPMS_PATCHER:-}"
    if [[ -z "$patcher" || ! -f "$patcher" ]]; then
        patcher="/opt/swtpm-toolkit/vm-build/modules/patch_libtpms.py"
        [[ -f "$patcher" ]] || patcher="$(dirname -- "${BASH_SOURCE[0]}")/patch_libtpms.py"
    fi

 local mfr_id tpm_model tpm_version ca_subject pcr_banks tpm_profile
    local reissuer_source="${TPM_EK_REISSUER_SOURCE:-${source_dir}/../libexec/swtpm-patch-reissue-ek-cert.py}"
    local aia_server_source="${TPM_AIA_SERVER_SOURCE:-${source_dir}/../libexec/swtpm-patch-tpm-aia-server.py}"
    local reissuer_install=/usr/local/libexec/swtpm-patch-reissue-ek-cert.py
    local aia_server_install=/usr/local/libexec/swtpm-patch-tpm-aia-server.py
    local aia_host=ftpm.amd.com
    local aia_port=8080
    local aia_route=/pki/aia/amd-ftpm-ca.cer
    local aia_uri="http://${aia_host}:${aia_port}${aia_route}"
    case "$vendor" in
        intel) mfr_id="id:494E5443"; tpm_model="TGL"; tpm_version="id:02580007"
               ca_subject="/CN=CSME TGL PTT  01SVN"; pcr_banks="sha256"
 tpm_profile='{"Name":"custom","StateFormatLevel":7,"Algorithms":"rsa,rsa-min-size=2048,sha1,hmac,aes,aes-min-size=128,mgf1,keyedhash,xor,sha256,sha384,null,rsassa,rsaes,rsapss,oaep,ecdsa,ecdh,ecdaa,ecschnorr,kdf1-sp800-56a,kdf1-sp800-108,kdf2,ecc,ecc-min-size=256,ecc-nist,symcipher,cmac,ctr,ofb,cbc,cfb,ecb","Commands":"0x11f-0x122,0x124,0x126-0x12b,0x12e,0x130-0x132,0x134-0x13f,0x142-0x151,0x153-0x159,0x15b-0x15e,0x160-0x165,0x167-0x174,0x176-0x178,0x17a-0x182,0x184-0x186,0x188-0x193"}' ;;
        amd|*) vendor="amd"; mfr_id="id:414D4400"; tpm_model="AMD"; tpm_version="id:00060300"
               ca_subject="/O=Advanced Micro Devices/CN=AMD fTPM CA"; pcr_banks="sha1,sha256"
               tpm_profile='{"Name": "default-v1"}' ;;
    esac

    if [[ "$vendor" == amd ]]; then
        if [[ ! -s "$reissuer_source" || ! -s "$aia_server_source" ]]; then
            _tpmp_warn "AMD EK AIA helpers are missing beside tpm-provision.sh"
            return 1
        fi
        if ! python3 -c 'import cryptography' >/dev/null 2>&1; then
            _tpmp_warn "python cryptography module is required for AMD EK certificate provisioning"
            return 1
        fi
        $ROOT_ESC install -Dm755 "$reissuer_source" "$reissuer_install" || return 1
        $ROOT_ESC install -Dm755 "$aia_server_source" "$aia_server_install" || return 1
    fi

    _tpmp_info "Provisioning ${vendor^^} swtpm identity (manufacturer + vendor string + EK cert + PCR banks)"

 # 1) libtpms patch
    if [[ -f "$patcher" ]]; then
        if ! $ROOT_ESC python3 "$patcher" --vendor "$vendor" --verify-only >/dev/null 2>&1; then
            _tpmp_info "Patching libtpms -> ${vendor^^} (manufacturer / vendor string / firmware)"
            if ! $ROOT_ESC python3 "$patcher" --vendor "$vendor"; then
                _tpmp_warn "patch_libtpms.py returned non-zero"
                return 1
            fi
            $ROOT_ESC ldconfig || return 1
            if ! $ROOT_ESC python3 "$patcher" --vendor "$vendor" --verify-only >/dev/null 2>&1; then
                _tpmp_warn "libtpms identity verification failed after patching"
                return 1
            fi
        else
            _tpmp_info "libtpms already ${vendor^^} (manufacturer + vendor string + firmware)"
        fi
    else
        _tpmp_warn "patch_libtpms.py not found ($patcher)"
        return 1
    fi

    local wrapper=/usr/local/bin/swtpm_patch_swtpm_wrapper
    $ROOT_ESC tee "$wrapper" >/dev/null <<WRAP || return 1
#!/bin/bash
# generated by tpm-provision.sh
args=()
skip_next=false
certificate_type=""
certificate_dir=""
for arg in "\$@"; do
    if \$skip_next; then skip_next=false; continue; fi
    case "\$arg" in
        --tpm-manufacturer|--tpm-model|--tpm-version) skip_next=true; continue ;;
        --tpm-manufacturer=*|--tpm-model=*|--tpm-version=*) continue ;;
        --type=*) certificate_type="\${arg#*=}" ;;
        --dir=*) certificate_dir="\${arg#*=}" ;;
    esac
    args+=("\$arg")
done
for ((i=0; i < \${#args[@]}; i++)); do
    case "\${args[i]}" in
        --type) ((i + 1 < \${#args[@]})) && certificate_type="\${args[i+1]}" ;;
        --dir)  ((i + 1 < \${#args[@]})) && certificate_dir="\${args[i+1]}" ;;
    esac
done
/usr/bin/swtpm_localca "\${args[@]}" \\
    --tpm-manufacturer ${mfr_id} \\
    --tpm-model ${tpm_model} \\
    --tpm-version ${tpm_version} || exit \$?

if [[ "${vendor}" == amd && "\$certificate_type" == ek ]]; then
    ek_certificate="\${certificate_dir%/}/ek.cert"
    if [[ -z "\$certificate_dir" || ! -s "\$ek_certificate" ]]; then
        echo "AMD EK certificate output was not created" >&2
        exit 1
    fi
    exec /usr/bin/python3 ${reissuer_install} \\
        --certificate "\$ek_certificate" \\
        --issuer-certificate /var/lib/swtpm-localca/issuercert.pem \\
        --issuer-key /var/lib/swtpm-localca/signkey.pem \\
        --aia-uri ${aia_uri}
fi
WRAP
    $ROOT_ESC chmod +x "$wrapper" || return 1
    if [[ "$vendor" == amd ]]; then
        $ROOT_ESC grep -Fq -- "--aia-uri ${aia_uri}" "$wrapper" || return 1
    fi

    local board_mfr board_model board_ver
    board_mfr=$($ROOT_ESC dmidecode -s baseboard-manufacturer 2>/dev/null || true)
    board_model=$($ROOT_ESC dmidecode -s baseboard-product-name 2>/dev/null || true)
    board_ver=$($ROOT_ESC dmidecode -s baseboard-version 2>/dev/null || true)
    [[ -n "$board_mfr"   ]] || board_mfr="${vendor^^}"
    [[ -n "$board_model" ]] || board_model="Desktop"
    [[ -n "$board_ver"   ]] || board_ver="1.0"
    $ROOT_ESC tee /etc/swtpm-localca.options >/dev/null <<OPTS || return 1
--platform-manufacturer ${board_mfr}
--platform-version ${board_ver}
--platform-model ${board_model}
OPTS

    local ca_dir=/var/lib/swtpm-localca
    local ca_key="$ca_dir/signkey.pem"
    local ca_certificate="$ca_dir/issuercert.pem"
    local have_ca_key=false have_ca_certificate=false
    $ROOT_ESC mkdir -p "$ca_dir" || return 1
    $ROOT_ESC test -s "$ca_key" && have_ca_key=true
    $ROOT_ESC test -s "$ca_certificate" && have_ca_certificate=true
    if [[ "$have_ca_key" != "$have_ca_certificate" ]]; then
        _tpmp_warn "incomplete SWTPM issuer CA: refusing to replace existing key or certificate"
        return 1
    fi
    if [[ "$have_ca_key" == false ]]; then
        if ! $ROOT_ESC openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 \
                -out "$ca_key" >/dev/null 2>&1 \
           || ! $ROOT_ESC openssl req -new -x509 -key "$ca_key" \
                -out "$ca_certificate" -days 3650 -subj "$ca_subject" \
                -addext "basicConstraints=critical,CA:TRUE" \
                -addext "keyUsage=critical,keyCertSign,cRLSign" \
                -addext "subjectKeyIdentifier=hash" \
                -addext "authorityKeyIdentifier=keyid:always" >/dev/null 2>&1; then
            _tpmp_warn "issuer CA generation failed"
            return 1
        fi
        echo 1 | $ROOT_ESC tee "$ca_dir/certserial" >/dev/null || return 1
        _tpmp_info "EK issuer CA: ${ca_subject#*CN=}"
    fi

    if ! $ROOT_ESC bash -s -- "$ca_certificate" "$ca_key" <<'VALIDATE_CA'
set -euo pipefail
certificate=$1
key=$2
openssl x509 -in "$certificate" -noout -checkend 0 >/dev/null
openssl pkey -in "$key" -noout >/dev/null
certificate_key=$(openssl x509 -in "$certificate" -pubkey -noout | openssl pkey -pubin -outform DER 2>/dev/null | sha256sum | awk '{print $1}')
private_key=$(openssl pkey -in "$key" -pubout -outform DER 2>/dev/null | sha256sum | awk '{print $1}')
[[ -n "$certificate_key" && "$certificate_key" == "$private_key" ]]
openssl x509 -in "$certificate" -noout -text | grep -q 'CA:TRUE'
openssl x509 -in "$certificate" -noout -text | grep -q 'Certificate Sign'
openssl verify -CAfile "$certificate" "$certificate" >/dev/null
VALIDATE_CA
    then
        _tpmp_warn "SWTPM issuer CA is expired, malformed, non-CA, or does not match its key"
        return 1
    fi

    $ROOT_ESC test -f "$ca_dir/certserial" || echo 1 | $ROOT_ESC tee "$ca_dir/certserial" >/dev/null || return 1
    $ROOT_ESC tee /etc/swtpm-localca.conf >/dev/null <<LOCALCACONF || return 1
statedir = ${ca_dir}
signingkey = ${ca_key}
issuercert = ${ca_certificate}
certserial = ${ca_dir}/certserial
LOCALCACONF

    if [[ "$vendor" == amd ]]; then
        local aia_root=/var/lib/swtpm-patch-tpm-aia
        local aia_certificate="${aia_root}${aia_route}"
        local aia_unit=/etc/systemd/system/swtpm-patch-tpm-aia.service
        local aia_gateway persistent_xml live_xml persistent_ips live_ips

        persistent_xml=$($ROOT_ESC virsh -c qemu:///system net-dumpxml default --inactive) || {
            _tpmp_warn "cannot read persistent libvirt default-network XML"
            return 1
        }
        aia_gateway=$(python3 -c '
import ipaddress, sys, xml.etree.ElementTree as ET
root = ET.fromstring(sys.stdin.read())
for node in root.findall("./ip"):
    address = node.get("address", "")
    try:
        if ipaddress.ip_address(address).version == 4:
            print(address)
            break
    except ValueError:
        pass
' <<<"$persistent_xml")
        if [[ -z "$aia_gateway" ]]; then
            _tpmp_warn "default libvirt network has no IPv4 gateway"
            return 1
        fi

        $ROOT_ESC mkdir -p "$(dirname -- "$aia_certificate")" || return 1
        $ROOT_ESC openssl x509 -in "$ca_certificate" -outform DER \
            -out "$aia_certificate" || return 1
        $ROOT_ESC chown root:root "$aia_certificate" || return 1
        $ROOT_ESC chmod 0755 "$aia_root" "$aia_root/pki" "$aia_root/pki/aia" || return 1
        $ROOT_ESC chmod 0444 "$aia_certificate" || return 1

        $ROOT_ESC tee "$aia_unit" >/dev/null <<AIAUNIT || return 1
[Unit]
Description=swtpm AMD TPM CA-Issuers endpoint
Wants=network-online.target
After=network-online.target libvirtd.service virtnetworkd.service

[Service]
Type=simple
DynamicUser=yes
ExecStartPre=/usr/bin/python3 ${aia_server_install} --bind ${aia_gateway} --port ${aia_port} --route ${aia_route} --host ${aia_host} --certificate ${aia_certificate} --check
ExecStart=/usr/bin/python3 ${aia_server_install} --bind ${aia_gateway} --port ${aia_port} --route ${aia_route} --host ${aia_host} --certificate ${aia_certificate}
Restart=always
RestartSec=2s
NoNewPrivileges=yes
CapabilityBoundingSet=
AmbientCapabilities=
PrivateDevices=yes
PrivateTmp=yes
ProtectHome=yes
ProtectSystem=strict
ProtectClock=yes
ProtectHostname=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectKernelLogs=yes
ProtectControlGroups=yes
ProtectProc=invisible
ProcSubset=pid
RestrictAddressFamilies=AF_INET
RestrictNamespaces=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
RemoveIPC=yes
LockPersonality=yes
MemoryDenyWriteExecute=yes
SystemCallArchitectures=native
SocketBindDeny=any
SocketBindAllow=ipv4:tcp:${aia_port}
TasksMax=16
LimitNOFILE=64
MemoryMax=64M
UMask=0077

[Install]
WantedBy=multi-user.target
AIAUNIT

        persistent_ips=$(_tpmp_dns_ips "$aia_host" <<<"$persistent_xml") || return 1
        if [[ -n "$persistent_ips" && "$persistent_ips" != "$aia_gateway" ]]; then
            _tpmp_warn "${aia_host} already has a conflicting persistent libvirt DNS mapping: ${persistent_ips//$'\n'/,}"
            return 1
        fi
        if [[ -z "$persistent_ips" ]]; then
            $ROOT_ESC virsh -c qemu:///system net-update default add dns-host \
                "<host ip='${aia_gateway}'><hostname>${aia_host}</hostname></host>" \
                --config || return 1
        fi
        persistent_xml=$($ROOT_ESC virsh -c qemu:///system net-dumpxml default --inactive) || return 1
        [[ "$(_tpmp_dns_ips "$aia_host" <<<"$persistent_xml")" == "$aia_gateway" ]] || {
            _tpmp_warn "persistent ${aia_host} DNS mapping did not validate after net-update"
            return 1
        }

        if $ROOT_ESC virsh -c qemu:///system net-list --name | grep -Fxq default; then
            live_xml=$($ROOT_ESC virsh -c qemu:///system net-dumpxml default) || return 1
            live_ips=$(_tpmp_dns_ips "$aia_host" <<<"$live_xml") || return 1
            if [[ -n "$live_ips" && "$live_ips" != "$aia_gateway" ]]; then
                _tpmp_warn "${aia_host} already has a conflicting live libvirt DNS mapping: ${live_ips//$'\n'/,}"
                return 1
            fi
            if [[ -z "$live_ips" ]]; then
                $ROOT_ESC virsh -c qemu:///system net-update default add dns-host \
                    "<host ip='${aia_gateway}'><hostname>${aia_host}</hostname></host>" \
                    --live || return 1
            fi
            live_xml=$($ROOT_ESC virsh -c qemu:///system net-dumpxml default) || return 1
            [[ "$(_tpmp_dns_ips "$aia_host" <<<"$live_xml")" == "$aia_gateway" ]] || {
                _tpmp_warn "live ${aia_host} DNS mapping did not validate after net-update"
                return 1
            }
        fi

        $ROOT_ESC systemctl daemon-reload || return 1
        $ROOT_ESC systemctl enable swtpm-patch-tpm-aia.service >/dev/null || return 1
        $ROOT_ESC systemctl restart swtpm-patch-tpm-aia.service || return 1
        $ROOT_ESC systemctl is-active --quiet swtpm-patch-tpm-aia.service || return 1
        if ! python3 - "$aia_gateway" "$aia_port" "$aia_route" "$aia_certificate" "$aia_host" <<'VERIFY_AIA'
import http.client
import sys
import time

address, port, route, certificate_path, expected_host = sys.argv[1:]
expected = open(certificate_path, "rb").read()
error = None
for _ in range(20):
    connection = None
    try:
        connection = http.client.HTTPConnection(address, int(port), timeout=1)
        connection.request("GET", route, headers={"Host": expected_host})
        response = connection.getresponse()
        received = response.read()
        if response.status != 200:
            raise RuntimeError(f"HTTP {response.status}")
        if response.version != 11:
            raise RuntimeError("AIA endpoint is not HTTP/1.1")
        if response.getheader("Content-Type") != "application/pkix-cert":
            raise RuntimeError("incorrect Content-Type")
        if response.getheader("Content-Length") != str(len(expected)):
            raise RuntimeError("incorrect Content-Length")
        if response.getheader("Server") is not None:
            raise RuntimeError("AIA endpoint exposes a Server fingerprint")
        if response.getheader("Date") is not None:
            raise RuntimeError("AIA endpoint exposes a Date fingerprint")
        if received != expected:
            raise RuntimeError("served certificate differs from installed DER")
        break
    except Exception as exc:
        error = exc
        time.sleep(0.25)
    finally:
        if connection is not None:
            connection.close()
else:
    raise SystemExit(f"AIA endpoint health check failed: {error}")
VERIFY_AIA
        then
            return 1
        fi
        _tpmp_info "AMD EK issuer endpoint active at ${aia_uri} (${aia_gateway}:${aia_port})"
    fi

 # 5b) microsoft mirror: detector-grade CAB with our issuer CA injected
 # the guest also needs the patch CA in LocalMachine\Root (see README notes)
    if [[ "$vendor" == amd ]]; then
        local ms_root=/var/lib/swtpm-patch-ms-mirror
        local ms_pki=/var/lib/swtpm-patch/pki
        local ms_unit=/etc/systemd/system/swtpm-patch-ms-mirror.service
        local ms_mirror_install=/usr/local/libexec/swtpm-patch-ms-mirror.py
        local forge_src="${source_dir}/swtpm-patch-forge-cab.py"
        local mirror_src="${TPM_MS_MIRROR_SOURCE:-${source_dir}/../libexec/swtpm-patch-ms-mirror.py}"
        local fwlink='https://go.microsoft.com/fwlink/?linkid=2097925'
        local orig_cab ms_cab ms_ca ms_cs ms_cskey
        command -v osslsigncode >/dev/null 2>&1 || { _tpmp_warn "osslsigncode is required for the microsoft mirror"; return 1; }
        [[ -f "$forge_src" && -f "$mirror_src" ]] || { _tpmp_warn "forge/mirror sources missing beside tpm-provision.sh"; return 1; }
        $ROOT_ESC mkdir -p "$ms_root" "$ms_pki"
        ms_ca="$ms_pki/patch-ca.pem"; ms_cs="$ms_pki/codesign.pem"; ms_cskey="$ms_pki/codesign.key"
        local ms_tls_cert="$ms_pki/ms-tls.pem" ms_tls_key="$ms_pki/ms-tls.key"
        if [[ ! -s "$ms_ca" ]]; then
            $ROOT_ESC openssl req -x509 -newkey rsa:3072 -keyout "${ms_ca%.pem}.key" -out "$ms_ca" -days 3650 -nodes \
                -subj "/CN=Windows Update Root" \
                -addext "basicConstraints=critical,CA:TRUE" -addext "keyUsage=critical,keyCertSign,cRLSign" >/dev/null 2>&1 || return 1
            _tpmp_info "patch CA generated"
        fi
        local ms_cert_specs="codesign|$ms_cs|$ms_cskey|codeSigning|Microsoft Corporation|
tls|$ms_tls_cert|$ms_tls_key|serverAuth|download.microsoft.com|DNS:download.microsoft.com,DNS:go.microsoft.com"
        while IFS='|' read -r nm cert key eku cn san; do
            [[ -z "$nm" ]] && continue
            if [[ ! -s "$cert" ]]; then
                $ROOT_ESC openssl req -newkey rsa:3072 -keyout "$key" -out "${cert%.pem}.csr" -nodes -subj "/CN=$cn" >/dev/null 2>&1 || return 1
                local ext="basicConstraints=CA:FALSE\nkeyUsage=digitalSignature,keyEncipherment\nextendedKeyUsage=$eku\nsubjectKeyIdentifier=hash\n"
                [[ -n "$san" ]] && ext="subjectAltName=$san\n$ext"
                printf "%b" "$ext" > "${cert%.pem}.ext"
                $ROOT_ESC openssl x509 -req -in "${cert%.pem}.csr" -CA "$ms_ca" -CAkey "${ms_ca%.pem}.key" -CAcreateserial \
                    -out "$cert" -days 1825 -extfile "${cert%.pem}.ext" >/dev/null 2>&1 || return 1
                rm -f "${cert%.pem}.ext"
                $ROOT_ESC rm -f "${cert%.pem}.csr"
            fi
        done <<<"$ms_cert_specs"
        orig_cab="$ms_root/TrustedTpm.orig.cab"
        if [[ ! -s "$orig_cab" ]]; then
            curl -sL --max-time 180 -A "Mozilla/5.0" -o "$orig_cab" "$fwlink" || return 1
        fi
        [[ -s "$orig_cab" ]] || { _tpmp_warn "TrustedTpm.cab download failed"; return 1; }
        $ROOT_ESC python3 "$forge_src" "$orig_cab" "$ca_certificate" "$ms_root/repacked.cab" >/dev/null || return 1
        $ROOT_ESC openssl x509 -in "$ca_certificate" -outform DER -out "$ms_root/issuer.der" || return 1
        osslsigncode sign -h sha256 -certs "$ms_cs" -key "$ms_cskey" -in "$ms_root/repacked.cab" -out "$ms_root/TrustedTpm.cab" >/dev/null 2>&1 || return 1
        osslsigncode verify -in "$ms_root/TrustedTpm.cab" -CAfile "$ms_ca" >/dev/null 2>&1 || { _tpmp_warn "forged CAB self-verify failed"; return 1; }
        $ROOT_ESC install -Dm755 "$mirror_src" "$ms_mirror_install" || return 1
        $ROOT_ESC tee "$ms_unit" >/dev/null <<MSUNIT || return 1
[Unit]
Description=swtpm patch microsoft mirror
After=network.target

[Service]
ExecStart=/usr/bin/python3 ${ms_mirror_install} --bind ${aia_gateway} --port 443 --cab ${ms_root}/TrustedTpm.cab --cert ${ms_tls_cert} --key ${ms_tls_key}
Restart=on-failure
DynamicUser=yes
AmbientCapabilities=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
PrivateTmp=yes
ProtectClock=yes
ProtectHostname=yes
ProtectKernelTunables=yes
ProtectKernelLogs=yes
RestrictAddressFamilies=AF_INET
TasksMax=16
LimitNOFILE=64
MemoryMax=64M
UMask=0077

[Install]
WantedBy=multi-user.target
MSUNIT
        $ROOT_ESC systemctl daemon-reload || return 1
        $ROOT_ESC systemctl enable --now swtpm-patch-ms-mirror.service || return 1
        sleep 1
        $ROOT_ESC systemctl is-active swtpm-patch-ms-mirror.service >/dev/null || { _tpmp_warn "ms-mirror service failed to start"; return 1; }
        for ms_host in go.microsoft.com download.microsoft.com; do
            local ms_ips
            persistent_xml=$($ROOT_ESC virsh -c qemu:///system net-dumpxml default --inactive) || return 1
            ms_ips=$(_tpmp_dns_ips "$ms_host" <<<"$persistent_xml") || return 1
            if [[ -z "$ms_ips" ]]; then
                $ROOT_ESC virsh -c qemu:///system net-update default modify dns-host \
                    "<host ip='${aia_gateway}'><hostname>${aia_host}</hostname><hostname>go.microsoft.com</hostname><hostname>download.microsoft.com</hostname></host>" \
                    --config --live >/dev/null 2>&1 || true
            fi
            persistent_xml=$($ROOT_ESC virsh -c qemu:///system net-dumpxml default --inactive) || return 1
            [[ "$(_tpmp_dns_ips "$ms_host" <<<"$persistent_xml")" == "$aia_gateway" ]] || {
                _tpmp_warn "persistent ${ms_host} DNS pin did not validate"
                return 1
            }
        done
        $ROOT_ESC install -Dm0644 "$ms_ca" /var/lib/swtpm-patch-tpm-aia/pki/aia/patch-ca.pem || return 1
        _tpmp_info "microsoft mirror active: forged CAB served at ${aia_gateway}:443"
    fi

    $ROOT_ESC tee /etc/swtpm_setup.conf >/dev/null <<SETUPCONF || return 1
# generated by swtpm-patch (${vendor^^})
create_certs_tool = ${wrapper}
create_certs_tool_config = /etc/swtpm-localca.conf
create_certs_tool_options = /etc/swtpm-localca.options
active_pcr_banks = ${pcr_banks}
rsa_keysize = 2048
profile = ${tpm_profile}
SETUPCONF

    local seed_dir
    seed_dir=$(mktemp -d -t swtpm-swtpm-seed.XXXXXXXX) || return 1
    if $ROOT_ESC swtpm_setup --tpmstate "$seed_dir" --tpm2 \
            --create-ek-cert --create-platform-cert --overwrite \
            --config /etc/swtpm_setup.conf --pcr-banks "$pcr_banks" >/dev/null 2>&1; then
        _tpmp_info "swtpm_setup validated: dual EK cert + ${pcr_banks} banks OK"
    else
        _tpmp_warn "swtpm_setup pre-seed returned non-zero"
        $ROOT_ESC rm -rf "$seed_dir" 2>/dev/null || true
        return 1
    fi
    $ROOT_ESC rm -rf "$seed_dir" 2>/dev/null || true

 # 8) chown tss, last on purpose, chowning before the pre-seed bricks fresh installs
    $ROOT_ESC chown -R tss:tss "$ca_dir" || return 1
    $ROOT_ESC chmod -R u+rwX "$ca_dir" || return 1
}
